import { Project } from "@/types";

export const initialProjects: Project[] = [
  {
    projectKey: "PRJ001",
    projectName: "Website Redesign",
    projectManager: "Eden",
    totalIssues: 100,
    issuesDone: 75,
    issuesInProgress: 20,
    totalStoryPoint: 130,
    storyPointsDone: 90,
    riskLevel: "medium risk",
    lastSyncedAt: "2025-05-19",
    developers: ["Alice Smith", "Bob Johnson"],
  },
  {
    projectKey: "PRJ002",
    projectName: "Car rental system",
    projectManager: "Thomas Wilson",
    totalIssues: 40,
    issuesDone: 23,
    issuesInProgress: 17,
    totalStoryPoint: 15,
    storyPointsDone: 5,
    riskLevel: "high risk",
    lastSyncedAt: "2025-05-15",
    developers: ["Emily Stone", "Liam Brown"],
  },
  {
    projectKey: "PRJ003",
    projectName: "Hotel management system",
    projectManager: "Eden",
    totalIssues: 34,
    issuesDone: 6,
    issuesInProgress: 28,
    totalStoryPoint: 35,
    storyPointsDone: 17,
    riskLevel: "high risk",
    lastSyncedAt: "2025-05-13",
    developers: ["Nina Taylor", "Daniel White"],
  },
  {
    projectKey: "PRJ004",
    projectName: "Technical approach system",
    projectManager: "Eden",
    totalIssues: 28,
    issuesDone: 24,
    issuesInProgress: 4,
    totalStoryPoint: 19,
    storyPointsDone: 6,
    riskLevel: "high risk",
    lastSyncedAt: "2025-05-09",
    developers: ["Carlos Garcia", "Olivia Moore"],
  },
  {
    projectKey: "PRJ005",
    projectName: "School management system",
    projectManager: "Assign reviewer",
    totalIssues: 44,
    issuesDone: 25,
    issuesInProgress: 19,
    totalStoryPoint: 55,
    storyPointsDone: 8,
    riskLevel: "medium risk",
    lastSyncedAt: "2025-04-30",
    developers: ["Sophia Hall", "Noah Lee"],
  },
  {
    projectKey: "PRJ006",
    projectName: "Inventory system",
    projectManager: "Sophia Martinez",
    totalIssues: 22,
    issuesDone: 5,
    issuesInProgress: 17,
    totalStoryPoint: 19,
    storyPointsDone: 1,
    riskLevel: "on track",
    lastSyncedAt: "2025-05-01",
    developers: ["Ethan Adams", "Grace Green"],
  },
  {
    projectKey: "PRJ007",
    projectName: "Mobile app",
    projectManager: "Johnaz Martinez",
    totalIssues: 25,
    issuesDone: 5,
    issuesInProgress: 20,
    totalStoryPoint: 19,
    storyPointsDone: 2,
    riskLevel: "high risk",
    lastSyncedAt: "2025-04-19",
    developers: ["Lucas Scott", "Mia Perez"],
  },
  {
    projectKey: "PRJ008",
    projectName: "Ride app",
    projectManager: "Samuel Martinez",
    totalIssues: 26,
    issuesDone: 6,
    issuesInProgress: 20,
    totalStoryPoint: 19,
    storyPointsDone: 1,
    riskLevel: "on track",
    lastSyncedAt: "2025-04-15",
    developers: ["Jack Miller", "Ava Davis"],
  },
  {
    projectKey: "PRJ009",
    projectName: "Farm management system",
    projectManager: "Joshua Filik",
    totalIssues: 35,
    issuesDone: 25,
    issuesInProgress: 10,
    totalStoryPoint: 18,
    storyPointsDone: 3,
    riskLevel: "on track",
    lastSyncedAt: "2025-04-29",
    developers: ["John Doe", "Jane Smith"],
  },
  {
    projectKey: "PRJ010",
    projectName: "Banking management system",
    projectManager: "Aban",
    totalIssues: 25,
    issuesDone: 4,
    issuesInProgress: 21,
    totalStoryPoint: 20,
    storyPointsDone: 4,
    riskLevel: "medium risk",
    lastSyncedAt: "2025-04-05",
    developers: ["Ryan King", "Zoe Morgan"],
  },
  {
    projectKey: "PRJ011",
    projectName: "Food delivery",
    projectManager: "John Doe",
    totalIssues: 15,
    issuesDone: 4,
    issuesInProgress: 11,
    totalStoryPoint: 17,
    storyPointsDone: 3,
    riskLevel: "on track",
    lastSyncedAt: "2025-04-22",
    developers: ["Ella Brown", "Henry Thompson"],
  },
];
