import { Project, Priority, Status } from "@/types";

export const initialProjects: Project[] = [
  {
    id: 1,
    name: "E-commerce Platform",
    description: "Platform for online product sales.",
    startDate: "2025-01-10",
    endDate: "2025-06-10",
    priority: Priority.High,
    status: Status.WorkInProgress,
    team: "Team Alpha",
  },
  {
    id: 2,
    name: "Marketing Website",
    description: "Showcase of company products and services.",
    startDate: "2025-02-15",
    endDate: "2025-04-22",
    priority: Priority.Medium,
    status: Status.Completed,
    team: "Team Beta",
  },
  {
    id: 3,
    name: "Mobile App Redesign",
    description: "UI/UX overhaul of the mobile application.",
    startDate: "2025-03-01",
    endDate: "2025-08-01",
    priority: Priority.Low,
    status: Status.ToDo,
    team: "Team Gamma",
  },
  {
    id: 4,
    name: "Internal Dashboard",
    description: "Performance tracking for internal teams.",
    startDate: "2025-04-05",
    endDate: "2025-07-15",
    priority: Priority.Medium,
    status: Status.WorkInProgress,
    team: "Team Alpha",
  },
  {
    id: 5,
    name: "AI Chatbot Integration",
    description: "Integrate chatbot for customer support automation.",
    startDate: "2025-05-01",
    endDate: "2025-09-05",
    priority: Priority.High,
    status: Status.UnderReview,
    team: "Team Beta",
  },
  {
    id: 6,
    name: "Security Audit",
    description: "Comprehensive audit of platform security.",
    startDate: "2025-05-12",
    endDate: "2025-06-30",
    priority: Priority.Urgent,
    status: Status.ToDo,
    team: "Team Gamma",
  },
  {
    id: 7,
    name: "Data Migration Plan",
    description: "Plan for legacy system data migration.",
    startDate: "2025-06-01",
    endDate: "2025-12-01",
    priority: Priority.Backlog,
    status: Status.ToDo,
    team: "Team Beta",
  },
  {
    id: 8,
    name: "Accessibility Improvements",
    description: "Enhancing accessibility compliance across the platform.",
    startDate: "2025-05-20",
    endDate: "2025-07-10",
    priority: Priority.Low,
    status: Status.UnderReview,
    team: "Team Alpha",
  },
  {
    id: 9,
    name: "Analytics Module Upgrade",
    description: "Upgrade analytics reporting features.",
    startDate: "2025-04-25",
    endDate: "2025-08-15",
    priority: Priority.Urgent,
    status: Status.WorkInProgress,
    team: "Team Gamma",
  },
  {
    id: 10,
    name: "Cloud Cost Optimization",
    description: "Reduce cloud infrastructure costs.",
    startDate: "2025-03-15",
    endDate: "2025-06-30",
    priority: Priority.Backlog,
    status: Status.Completed,
    team: "Team Beta",
  },
];
